--CREATE SCHEMA ntt;

SET SCHEMA NTT;

--DROP TABLE NotificationTypes CASCADE;
CREATE COLUMN TABLE NotificationTypes ( 
    QMART      VARCHAR(2),
    QMART_TEXT VARCHAR(40), 
    PRIMARY KEY (QMART)
  ); 

CREATE COLUMN TABLE OrderTypes ( 
    AUART      VARCHAR(4),
    AUTYP      VARCHAR(2), 
    AUART_TEXT VARCHAR(40), 
    PRIMARY KEY (AUART)
  ); 

CREATE COLUMN TABLE Materials ( 
    MATNR      VARCHAR(20),
    MATNR_TEXT VARCHAR(40), 
    PRIMARY KEY (MATNR)
  ); 

CREATE COLUMN TABLE Customers ( 
    KUNNR      VARCHAR(12),
    KUNNR_TEXT VARCHAR(40), 
    PRIMARY KEY (KUNNR)
  ); 

CREATE COLUMN TABLE Users ( 
    UNAME       VARCHAR(12),
    UNAME_TEXT  VARCHAR(80), 
    PRIMARY KEY (UNAME)
  ); 

CREATE COLUMN TABLE IssueStatus ( 
    IPHAS     VARCHAR(1),
    IPHAS_TEXT VARCHAR(40), 
    PRIMARY KEY (IPHAS)
  ); 
  
CREATE COLUMN TABLE IssuePriority ( 
    PRIOK      VARCHAR(1),
    PRIOK_TEXT VARCHAR(40), 
    PRIMARY KEY (PRIOK)
  ); 
  
CREATE COLUMN TABLE Plants ( 
    WERKS      VARCHAR(4),
    WERKS_TEXT VARCHAR(40), 
    PRIMARY KEY (WERKS)
  ); 